language: python
services:
  - redis-server
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=docs
